# Generated by Django 2.2.2 on 2019-06-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.PositiveIntegerField()),
                ('source', models.CharField(blank=True, max_length=11, null=True)),
                ('destination', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'unique_together': {('type', 'call_id')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(max_length=10)),
                ('month', models.IntegerField(default=6)),
                ('year', models.IntegerField(default=2019)),
                ('price', models.CharField(max_length=10)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_destination', to='call.Call')),
            ],
        ),
    ]
